#################### FIND THE DIFFERENCE ####################

# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add 
# one more letter at a random position.

# Find the letter that was added in t.

# Example:
# Input:
# s = "abcd"
# t = "abcde"
# Output:
# e
# Explanation:
# 'e' is the letter that was added.


#################### SOLUTION ####################
# @param {String} s
# @param {String} t
# @return {Character}
# TIME: O(n) -- SPACE: O(n)
def find_the_difference(s, t)
  h = Hash.new{|h,char| h[char] = 0}
  for i in 0...s.length
    h[s[i]] += 1
  end

  for i in 0...t.length
    if h.has_key?(t[i])
      h[t[i]] -= 1
      return t[i] if h[t[i]] == -1
    else
      return t[i]
    end
  end
end

s1 = "abcd"
t1 = "abcde"
s2 = "aaaajlkrejoijdlkgj"
t2 = "jkdgliajerajojalkaz"
s3 = "aaabbbeeeeeee"
t3 = "aeeaabebeeebee"
s4 = "a"
t4 = "aa"
s5 = ""
t5 = "t"
s6 = "aaaaa"
t6 = "aabaaa"

puts "Expected: e -- Actual: #{find_the_difference(s1, t1)}"
puts "Expected: z -- Actual: #{find_the_difference(s2, t2)}"
puts "Expected: e -- Actual: #{find_the_difference(s3, t3)}"
puts "Expected: a -- Actual: #{find_the_difference(s4, t4)}"
puts "Expected: t -- Actual: #{find_the_difference(s5, t5)}"
puts "Expected: b -- Actual: #{find_the_difference(s6, t6)}"