num = 3
str = "a"

p str * num

abbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbb
abbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbbabbbbbbbbbbbb